class Player:

    def __init__(self, id: int, cash: int, color: str): ...

    def get_id(self) -> int: ...

    def get_cash(self) -> int: ...

    def get_color(self) -> str: ...

    def update_cash(self, value: int) -> None: ...
